name: build
run-name: Build fw
on:
  push:
    branches:
    - main
    - 'releases/**'
jobs:
  build-left-side:
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.30.0
    steps:
      - uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE && tinygo build -target nicenano -size short -o corne_left_nano.uf2 github.com/funkycode/tinygo-corne/nicenano/left

