name: build
run-name: Build fw
on:
  push:
    branches:
    - main
    - 'releases/**'
jobs:
  # checkounte:
  #   runs-on: ubuntu-latest
  #   container:
  #     volumes:
  #       - /src:/home/github
  #   steps:
  #     - uses: actions/checkout@v4
  build:
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.30.0
      options: --user root
      env:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/tinygo/bin:/usr/local/go/bin"
        GITHUB_WORKSPACE: "/src/nano"
      # volumes:
      #   - /src:/home/github
    steps:
      - uses: actions/checkout@v4
      - run: cd $GITHUB_WORKSPACE && ls -l 
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE
      - run: git config --global --add safe.directory /root/go/pkg/mod/
      - name: build left side
        run: tinygo build -target nicenano -size short -o corne_left_nano.uf2 github.com/funkycode/tinygo-corne/nicenano/left
      - uses: actions/upload-artifact@v3
        with:
          name: corne_left_nano.uf2
          path: corne_left_nano.uf2
      - name: build right side
        run: tinygo build -target nicenano -size short -o corne_right_nano.uf2 github.com/funkycode/tinygo-corne/nicenano/right
      - uses: actions/upload-artifact@v3
        with:
          name: corne_right_nano.uf2
          path: corne_right_nano.uf2

